config/routes.rb
Rails.application.routes.draw do

  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
belongs_to :restaurant

validates :content, presence: true
validates :rating, presence: true
validates :rating, inclusion: { in: [0,1,2,3,4,5], allow_nil: false }
validates :rating, numericality: { only_integer: true}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :review]



  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end

  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
  def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create

    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)

    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def  review_params
      params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<div class="container">

  <h1>This is the list of our restaurants:</h1>
  <% @restaurants.each do |restaurant| %>
    <h3> <%=  link_to restaurant.name, restaurant%> </h3>
      <ul>
        <li><%= restaurant.address %></li>
        <li><%= restaurant.phone_number %></li>
        <li><%= restaurant.category %></li>
      </ul>
  <%end%>

  <%=  link_to "Add a new restaurant" , new_restaurant_path%>
</div>

app/views/restaurants/new.html.erb
<div class="container">

  <%= simple_form_for [@restaurant] do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, placeholder: 'Please, choose between chinese, italian, japanese, french or belgian' %>
    <%= f.submit "Add new restaurant" %>
  <% end %>

</div>

app/views/restaurants/show.html.erb
<div class="container">


    <h1> <%= @restaurant.name%> </h1>
      <ul>
        <li><%= @restaurant.address %></li>
        <li><%= @restaurant.phone_number %></li>
        <li><%= @restaurant.category %></li>
      </ul>


    <ul>
      <% @restaurant.reviews.each do |review, rating| %>
        <li><%= review.content %> - <%= review.rating%></li>
      <% end %>
       <li> <%= link_to "Add a review", new_restaurant_review_path(@restaurant) %> </li>
    </ul>

</div>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="container">

  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, placeholder: "rate from 0 to 5" %>
    <%= f.submit "Create your review" %>
  <% end %>

</div>